// megafunction wizard: %ALTECC%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altecc_encoder 

// ============================================================
// File Name: altecc_enc32_26.v
// Megafunction Name(s):
// 			altecc_encoder
//
// Simulation Library Files(s):
// 			
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.0 Build 156 04/24/2013 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altecc_encoder CBX_AUTO_BLACKBOX="ALL" device_family="Cyclone IV GX" lpm_pipeline=0 width_codeword=32 width_dataword=26 data q
//VERSION_BEGIN 13.0 cbx_altecc_encoder 2013:04:24:18:08:47:SJ cbx_mgl 2013:04:24:18:11:10:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  altecc_enc32_26_altecc_encoder_4jb
	( 
	data,
	q) ;
	input   [25:0]  data;
	output   [31:0]  q;

	wire  [25:0]  data_wire;
	wire  [14:0]  parity_01_wire;
	wire  [7:0]  parity_02_wire;
	wire  [3:0]  parity_03_wire;
	wire  [1:0]  parity_04_wire;
	wire  [0:0]  parity_05_wire;
	wire  [30:0]  parity_final_wire;
	wire  [31:0]  q_wire;

	assign
		data_wire = data,
		parity_01_wire = {(data_wire[25] ^ parity_01_wire[13]), (data_wire[23] ^ parity_01_wire[12]), (data_wire[21] ^ parity_01_wire[11]), (data_wire[19] ^ parity_01_wire[10]), (data_wire[17] ^ parity_01_wire[9]), (data_wire[15] ^ parity_01_wire[8]), (data_wire[13] ^ parity_01_wire[7]), (data_wire[11] ^ parity_01_wire[6]), (data_wire[10] ^ parity_01_wire[5]), (data_wire[8] ^ parity_01_wire[4]), (data_wire[6] ^ parity_01_wire[3]), (data_wire[4] ^ parity_01_wire[2]), (data_wire[3] ^ parity_01_wire[1]), (data_wire[1] ^ parity_01_wire[0]), data_wire[0]},
		parity_02_wire = {((data_wire[24] ^ data_wire[25]) ^ parity_02_wire[6]), ((data_wire[20] ^ data_wire[21]) ^ parity_02_wire[5]), ((data_wire[16] ^ data_wire[17]) ^ parity_02_wire[4]), ((data_wire[12] ^ data_wire[13]) ^ parity_02_wire[3]), ((data_wire[9] ^ data_wire[10]) ^ parity_02_wire[2]), ((data_wire[5] ^ data_wire[6]) ^ parity_02_wire[1]), ((data_wire[2] ^ data_wire[3]) ^ parity_02_wire[0]), data_wire[0]},
		parity_03_wire = {((((data_wire[22] ^ data_wire[23]) ^ data_wire[24]) ^ data_wire[25]) ^ parity_03_wire[2]), ((((data_wire[14] ^ data_wire[15]) ^ data_wire[16]) ^ data_wire[17]) ^ parity_03_wire[1]), ((((data_wire[7] ^ data_wire[8]) ^ data_wire[9]) ^ data_wire[10]) ^ parity_03_wire[0]), ((data_wire[1] ^ data_wire[2]) ^ data_wire[3])},
		parity_04_wire = {((((((((data_wire[18] ^ data_wire[19]) ^ data_wire[20]) ^ data_wire[21]) ^ data_wire[22]) ^ data_wire[23]) ^ data_wire[24]) ^ data_wire[25]) ^ parity_04_wire[0]), ((((((data_wire[4] ^ data_wire[5]) ^ data_wire[6]) ^ data_wire[7]) ^ data_wire[8]) ^ data_wire[9]) ^ data_wire[10])},
		parity_05_wire = {((((((((((((((data_wire[11] ^ data_wire[12]) ^ data_wire[13]) ^ data_wire[14]) ^ data_wire[15]) ^ data_wire[16]) ^ data_wire[17]) ^ data_wire[18]) ^ data_wire[19]) ^ data_wire[20]) ^ data_wire[21]) ^ data_wire[22]) ^ data_wire[23]) ^ data_wire[24]) ^ data_wire[25])},
		parity_final_wire = {(q_wire[30] ^ parity_final_wire[29]), (q_wire[29] ^ parity_final_wire[28]), (q_wire[28] ^ parity_final_wire[27]), (q_wire[27] ^ parity_final_wire[26]), (q_wire[26] ^ parity_final_wire[25]), (q_wire[25] ^ parity_final_wire[24]), (q_wire[24] ^ parity_final_wire[23]), (q_wire[23] ^ parity_final_wire[22]), (q_wire[22] ^ parity_final_wire[21]), (q_wire[21] ^ parity_final_wire[20]), (q_wire[20] ^ parity_final_wire[19]), (q_wire[19] ^ parity_final_wire[18]), (q_wire[18] ^ parity_final_wire[17]), (q_wire[17] ^ parity_final_wire[16]), (q_wire[16] ^ parity_final_wire[15]), (q_wire[15] ^ parity_final_wire[14]), (q_wire[14] ^ parity_final_wire[13]), (q_wire[13] ^ parity_final_wire[12]), (q_wire[12] ^ parity_final_wire[11]), (q_wire[11] ^ parity_final_wire[10]), (q_wire[10] ^ parity_final_wire[9]), (q_wire[9] ^ parity_final_wire[8]), (q_wire[8] ^ parity_final_wire[7]), (q_wire[7] ^ parity_final_wire[6]), (q_wire[6] ^ parity_final_wire[5]), (q_wire[5] ^ parity_final_wire[4]), (q_wire[4] ^ parity_final_wire[3]), (q_wire[3] ^ parity_final_wire[2]), (q_wire[2] ^ parity_final_wire[1]), (q_wire[1] ^ parity_final_wire[0]), q_wire[0]},
		q = q_wire,
		q_wire = {parity_final_wire[30], parity_05_wire[0], parity_04_wire[1], parity_03_wire[3], parity_02_wire[7], parity_01_wire[14], data_wire};
endmodule //altecc_enc32_26_altecc_encoder_4jb
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module altecc_enc32_26 (
	data,
	q);

	input	[25:0]  data;
	output	[31:0]  q;

	wire [31:0] sub_wire0;
	wire [31:0] q = sub_wire0[31:0];

	altecc_enc32_26_altecc_encoder_4jb	altecc_enc32_26_altecc_encoder_4jb_component (
				.data (data),
				.q (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV GX"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV GX"
// Retrieval info: CONSTANT: lpm_pipeline NUMERIC "0"
// Retrieval info: CONSTANT: width_codeword NUMERIC "32"
// Retrieval info: CONSTANT: width_dataword NUMERIC "26"
// Retrieval info: USED_PORT: data 0 0 26 0 INPUT NODEFVAL "data[25..0]"
// Retrieval info: USED_PORT: q 0 0 32 0 OUTPUT NODEFVAL "q[31..0]"
// Retrieval info: CONNECT: @data 0 0 26 0 data 0 0 26 0
// Retrieval info: CONNECT: q 0 0 32 0 @q 0 0 32 0
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc54_47_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc72_64_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL altecc_enc32_26_bb.v TRUE
